### PR TITLE
Added reverse a string solution

### PR DESCRIPTION
**Pull request by rahul-n18**
I Have added 3 ways in which we can reverse a String .
fixes issue #1

### CODE REVIEW

**Comment by Zohaib-Sathio** [comment]
> I Have added 3 ways in which we can reverse a String . fixes issue #1

@rahul-n18 Kindly add Cpp source code files (.cpp) not the txt document!

**Comment by rahul-n18** [comment]
Oops Ill Change it

**Comment by rahul-n18** [comment]
I have added .cpp files

**Comment by Zohaib-Sathio** [comment]
> I have added .cpp files

@rahul-n18 Your PR has been merged successfully, Thank you for your contribution.
Give repo a star if it was useful.
Happy hacking.

**Comment by rahul-n18** [comment]
yes i will

**Pull request merged**
