### PR TITLE
Create RemoveDuplicates.java

### LINKED ISSUE #31: Integer array without duplicates
A program given an input integer array which then returns an integer array without any duplicates

### LINKED ISSUE #35: Total sum of the Binary Tree
A program which finds total sum of the binary tree

### PR DESCRIPTION
**Pull request by AaryanSingh0017**

### CODE REVIEW

**Comment by Zohaib-Sathio** [comment]
> _ No description provided. _

@AaryanSingh0017 your code implemention is right but for only sorted array, Kindly change your algorithm so that it can remove duplicates from an unsorted array. 
Hint: You can first sort array then use this algorithm!

**Comment by AaryanSingh0017** [comment]
ok

**Comment by AaryanSingh0017** [comment]
I have made the necessary changes, kindly review it.

**Comment by Zohaib-Sathio** [comment]
@AaryanSingh0017 Your PR has been merged successfully, Thank you for your contribution.
Give repo a star if it was useful.
Happy hacking.

**Pull request merged**
